[package]
name = "shadow-respawn"
version = "0.1.0"
authors = ["Shadow"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
